// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOdfCwr9KTBuw0vpLoWb8Z5Qti2Wa2RPE',
    appId: '1:708070340760:web:254689de180abf6705b8ed',
    messagingSenderId: '708070340760',
    projectId: 'soongflix-1c197',
    authDomain: 'soongflix-1c197.firebaseapp.com',
    storageBucket: 'soongflix-1c197.appspot.com',
    measurementId: 'G-DFNXBMFE7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBctlKDfuRFPE593Y2RwQIigigSe6WRDng',
    appId: '1:708070340760:android:53551dc5669161d505b8ed',
    messagingSenderId: '708070340760',
    projectId: 'soongflix-1c197',
    storageBucket: 'soongflix-1c197.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ9jjA7ndUvd6IOTIH8b9AALxLWnkynMw',
    appId: '1:708070340760:ios:b54b206256fb0dda05b8ed',
    messagingSenderId: '708070340760',
    projectId: 'soongflix-1c197',
    storageBucket: 'soongflix-1c197.appspot.com',
    iosClientId: '708070340760-qm64i1a633th70tk0t9hgv8ljlbmt719.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ9jjA7ndUvd6IOTIH8b9AALxLWnkynMw',
    appId: '1:708070340760:ios:b54b206256fb0dda05b8ed',
    messagingSenderId: '708070340760',
    projectId: 'soongflix-1c197',
    storageBucket: 'soongflix-1c197.appspot.com',
    iosClientId: '708070340760-qm64i1a633th70tk0t9hgv8ljlbmt719.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexflix',
  );
}
